package app

import (
	"bytes"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"relationship/internal/config"
)

// newTestApp assembles a full App against a throwaway database. Async
// extraction and the backup schedule stay off: the contract test must be
// deterministic, not a race between the router and a background worker.
func newTestApp(t *testing.T) *App {
	t.Helper()
	dir := t.TempDir()
	cfg := &config.Config{
		Server:   config.ServerConfig{Host: "127.0.0.1", Port: 0},
		Database: config.DatabaseConfig{Path: filepath.Join(dir, "contract.db")},
		LLM: config.LLMConfig{
			Endpoint:     "http://127.0.0.1:1",
			Protocol:     "openai",
			ExtractModel: "test",
			AdviceModel:  "test",
			EmbedModel:   "test",
			EmbedDim:     8,
			AsyncExtract: false,
			AllowRemote:  false,
		},
		Backup: config.BackupConfig{Enabled: false, Dir: filepath.Join(dir, "backups")},
	}
	a, err := New(cfg, filepath.Join(dir, "config.yaml"))
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	t.Cleanup(func() { a.Close() })
	return a
}

// TestAPIRouteContract pins the API surface to a golden file. A route change
// that does not update routes.golden.txt fails CI instead of silently breaking
// the frontend; regenerating deliberately is `LOOM_UPDATE_GOLDEN=1 go test ./internal/app/`.
// docs/architecture/api.md must be updated in the same change.
func TestAPIRouteContract(t *testing.T) {
	a := newTestApp(t)
	e, err := a.NewRouter()
	if err != nil {
		t.Fatalf("NewRouter: %v", err)
	}

	var lines []string
	for _, r := range e.Routes() {
		if strings.HasPrefix(r.Path, "/api") {
			lines = append(lines, r.Method+" "+r.Path)
		}
	}
	sort.Strings(lines)
	got := "# Generated by TestAPIRouteContract. Updating this file requires updating\n# docs/architecture/api.md in the same change.\n" + strings.Join(lines, "\n") + "\n"

	golden := filepath.Join("routes.golden.txt")
	if os.Getenv("LOOM_UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(golden, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run LOOM_UPDATE_GOLDEN=1 to regenerate): %v", err)
	}
	if got != string(want) {
		t.Fatalf("API surface drifted from routes.golden.txt.\n--- want ---\n%s\n--- got ---\n%s", want, got)
	}
}

// TestAPIErrorEnvelope pins the error contract: every /api failure speaks
// {ok:false, error:{code,message}} and carries the API version header.
func TestAPIErrorEnvelope(t *testing.T) {
	a := newTestApp(t)
	e, err := a.NewRouter()
	if err != nil {
		t.Fatalf("NewRouter: %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/api/persons/does-not-exist", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)

	if rec.Code != http.StatusNotFound {
		t.Fatalf("status = %d, want 404", rec.Code)
	}
	if v := rec.Header().Get("X-API-Version"); v != APIVersion {
		t.Fatalf("X-API-Version = %q, want %q", v, APIVersion)
	}
	body := rec.Body.String()
	for _, fragment := range []string{`"ok":false`, `"code":"NOT_FOUND"`, `"message":`} {
		if !strings.Contains(body, fragment) {
			t.Fatalf("error envelope missing %s in %s", fragment, body)
		}
	}
}

// TestAPIVersionHeaderOnSuccess keeps the happy path honest too: the version
// header is contract metadata, not an error-path detail.
func TestAPIVersionHeaderOnSuccess(t *testing.T) {
	a := newTestApp(t)
	e, err := a.NewRouter()
	if err != nil {
		t.Fatalf("NewRouter: %v", err)
	}

	req := httptest.NewRequest(http.MethodGet, "/api/persons", nil)
	rec := httptest.NewRecorder()
	e.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200 (body: %s)", rec.Code, rec.Body.String())
	}
	if v := rec.Header().Get("X-API-Version"); v != APIVersion {
		t.Fatalf("X-API-Version = %q, want %q", v, APIVersion)
	}
	if !bytes.Contains(rec.Body.Bytes(), []byte(`"ok":true`)) {
		t.Fatalf("success envelope missing ok:true: %s", rec.Body.String())
	}
}
